vim.keymap.set("n", "<C-e>", vim.cmd.Ex)
vim.keymap.set("t", "<Esc>", "<C-\\><C-n>")
vim.keymap.set("i", "jk", "<Esc>")
vim.keymap.set("n", "<S-k>", "<C-u>", {noremap=true})
vim.keymap.set("n", "<S-j>", "<C-d>", {noremap=true})
vim.keymap.set("x", "<S-k>", "<C-u>", {noremap=true})
vim.keymap.set("x", "<S-j>", "<C-d>", {noremap=true})
vim.keymap.set("x", "<Tab>", ">><CR>", {noremap=true})
vim.keymap.set("x", "<S-Tab>", "<<<CR>", {noremap=true})
vim.keymap.set("n", "<Tab>", ">>", {noremap=true})
vim.keymap.set("n", "<S-Tab>", "<<", {noremap=true})
vim.keymap.set("n", "<S-u>", "<C-r>", {noremap=true})
vim.keymap.set("n", "<C-t>", ":terminal<CR>", {noremap=true})
vim.keymap.set("n", "<C-n>", ":bprev<CR>", {noremap=true})
vim.keymap.set("n", "<C-m>", ":bnext<CR>", {noremap=true})
vim.keymap.set("v", "/", "y/<C-r>\"", {noremap=true})
vim.keymap.set("v", "?", "y?<C-r>\"", {noremap=true})

vim.keymap.set("x", "<leader>p", "\"_dP")
vim.keymap.set("n", "<leader>y", "\"+y")
vim.keymap.set("v", "<leader>y", "\"+y")
vim.keymap.set("n", "<leader>Y", "\"+Y")
vim.keymap.set("n", "<leader>d", "\"_d")
